Repository scanoss/papi, pull requests merged in 2025-08, with the labels that each got.

#34 [SP-3080] feat: add date field to component version response, change component methods to GET
  api/componentsv2/scanoss-components.pb.go
  api/componentsv2/scanoss-components.pb.gw.go
  protobuf/scanoss/api/components/v2/scanoss-components.proto
  protobuf/scanoss/api/components/v2/scanoss-components.swagger.json
Labels: enhancement

#35 chore:SP-3127 Removes '/api' prefix from vulnerability and dependency…
  CHANGELOG.md
  api/componentsv2/scanoss-components.pb.go
  api/componentsv2/scanoss-components.pb.gw.go
  api/dependenciesv2/scanoss-dependencies.pb.go
  api/dependenciesv2/scanoss-dependencies.pb.gw.go
  api/vulnerabilitiesv2/scanoss-vulnerabilities.pb.go
  api/vulnerabilitiesv2/scanoss-vulnerabilities.pb.gw.go
  protobuf/scanoss/api/components/v2/scanoss-components.proto
  protobuf/scanoss/api/components/v2/scanoss-components.swagger.json
  protobuf/scanoss/api/dependencies/v2/scanoss-dependencies.proto
  protobuf/scanoss/api/dependencies/v2/scanoss-dependencies.swagger.json
  protobuf/scanoss/api/vulnerabilities/v2/README.md
  protobuf/scanoss/api/vulnerabilities/v2/scanoss-vulnerabilities.proto
  protobuf/scanoss/api/vulnerabilities/v2/scanoss-vulnerabilities.swagger.json
Labels: documentation, enhancement

#36 chore: Adds missing 0.14.0 version to CHANGELOG.md file
  CHANGELOG.md
Labels: documentation

#37 chore:SP-3133 Adds 'json_name' to protobuf definitions to keep compat…
  CHANGELOG.md
  api/componentsv2/scanoss-components.pb.go
  api/cryptographyv2/scanoss-cryptography.pb.go
  api/dependenciesv2/scanoss-dependencies.pb.go
  api/licensesv2/scanoss-licenses.pb.go
  api/scanningv2/scanoss-scanning.pb.go
  api/vulnerabilitiesv2/scanoss-vulnerabilities.pb.go
  protobuf/scanoss/api/components/v2/scanoss-components.proto
  protobuf/scanoss/api/components/v2/scanoss-components.swagger.json
  protobuf/scanoss/api/cryptography/v2/scanoss-cryptography.proto
  protobuf/scanoss/api/cryptography/v2/scanoss-cryptography.swagger.json
  protobuf/scanoss/api/dependencies/v2/scanoss-dependencies.proto
  protobuf/scanoss/api/dependencies/v2/scanoss-dependencies.swagger.json
  protobuf/scanoss/api/geoprovenance/v2/scanoss-geoprovenance.swagger.json
  protobuf/scanoss/api/licenses/v2/scanoss-licenses.proto
  protobuf/scanoss/api/licenses/v2/scanoss-licenses.swagger.json
  protobuf/scanoss/api/scanning/v2/scanoss-scanning.proto
  protobuf/scanoss/api/scanning/v2/scanoss-scanning.swagger.json
  protobuf/scanoss/api/vulnerabilities/v2/scanoss-vulnerabilities.proto
  protobuf/scanoss/api/vulnerabilities/v2/scanoss-vulnerabilities.swagger.json
  scripts/proto-build.sh
Labels: bug, enhancement
